# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-20 20:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0028_auto_20151016_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildresult',
            name='result_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='buildresult',
            name='service_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='buildresult',
            name='setup_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
