# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 10:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0031_convert_log_data_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildresult',
            name='after_log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
